//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace playtarky.Resources.Forms.MainForm.TabContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TabContentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabContentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("playtarky.Resources.Forms.MainForm.TabContent.TabContentResource", typeof(TabContentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BepInEx/plugins.
        /// </summary>
        internal static string BepInExPluginsTabTitle {
            get {
                return ResourceManager.GetString("BepInExPluginsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All Items.
        /// </summary>
        internal static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected Items.
        /// </summary>
        internal static string ExportSelected {
            get {
                return ResourceManager.GetString("ExportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import All Items.
        /// </summary>
        internal static string ImportAll {
            get {
                return ResourceManager.GetString("ImportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Selected Items.
        /// </summary>
        internal static string ImportSelected {
            get {
                return ResourceManager.GetString("ImportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher Info.
        /// </summary>
        internal static string LauncherInfoTabTitle {
            get {
                return ResourceManager.GetString("LauncherInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Click / CTRL+Click to select multiple items. DEL to delete selected files..
        /// </summary>
        internal static string ListBoxHelper {
            get {
                return ResourceManager.GetString("ListBoxHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in File Explorer.
        /// </summary>
        internal static string OpenFileExplorer {
            get {
                return ResourceManager.GetString("OpenFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string ProfilesTabTitle {
            get {
                return ResourceManager.GetString("ProfilesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Info.
        /// </summary>
        internal static string ServerInfoTabTitle {
            get {
                return ResourceManager.GetString("ServerInfoTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/mods.
        /// </summary>
        internal static string UserModTabTitle {
            get {
                return ResourceManager.GetString("UserModTabTitle", resourceCulture);
            }
        }
    }
}
