//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace playtarky.Resources.Forms.CreateProfileForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateProfileFormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateProfileFormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("playtarky.Resources.Forms.CreateProfileForm.CreateProfileFormResource", typeof(CreateProfileFormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fika Compatibility.
        /// </summary>
        internal static string FikaGroupBoxTitle {
            get {
                return ResourceManager.GetString("FikaGroupBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options will allow fika versions to be displayed on the profile and the ability for the profile to be exported as a fika client package for friends using this app..
        /// </summary>
        internal static string FikaHelp {
            get {
                return ResourceManager.GetString("FikaHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Profile.
        /// </summary>
        internal static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Profile is a Fika Host.
        /// </summary>
        internal static string IsFikaHost {
            get {
                return ResourceManager.GetString("IsFikaHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile {0} already exists, do you wish to overwrite it?.
        /// </summary>
        internal static string ProfileAlreadyExists {
            get {
                return ResourceManager.GetString("ProfileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Already Exists.
        /// </summary>
        internal static string ProfileAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("ProfileAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Profile Uses Fika.
        /// </summary>
        internal static string UsesFika {
            get {
                return ResourceManager.GetString("UsesFika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile name is invalid. The profile name should contain 4 to 32 characters comprising letters, numbers, underscores, and hyphens only, starting with a letter or number only..
        /// </summary>
        internal static string ValidationFailedMsg {
            get {
                return ResourceManager.GetString("ValidationFailedMsg", resourceCulture);
            }
        }
    }
}
