//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace playtarky.Resources.Forms.MainForm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainFormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainFormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("playtarky.Resources.Forms.MainForm.MainFormResource", typeof(MainFormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile {0} was created successfully. Would you like to make it your active profile now?.
        /// </summary>
        internal static string ActivateProfileText {
            get {
                return ResourceManager.GetString("ActivateProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Profile?.
        /// </summary>
        internal static string ActivateProfileTitle {
            get {
                return ResourceManager.GetString("ActivateProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Profile.
        /// </summary>
        internal static string ActiveProfile {
            get {
                return ResourceManager.GetString("ActiveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The previously active profile {0} was not found. The application will continue without a profile..
        /// </summary>
        internal static string ActiveProfileMissingMsg {
            get {
                return ResourceManager.GetString("ActiveProfileMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Profile Missing.
        /// </summary>
        internal static string ActiveProfileMissingTitle {
            get {
                return ResourceManager.GetString("ActiveProfileMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Files...
        /// </summary>
        internal static string CopyingFiles {
            get {
                return ResourceManager.GetString("CopyingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crash report has been created:.
        /// </summary>
        internal static string CrashReportCreated {
            get {
                return ResourceManager.GetString("CrashReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Profile....
        /// </summary>
        internal static string CreatingProfile {
            get {
                return ResourceManager.GetString("CreatingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ErrorCAPS {
            get {
                return ResourceManager.GetString("ErrorCAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Creating Profile.
        /// </summary>
        internal static string ErrorCreatingProfile {
            get {
                return ResourceManager.GetString("ErrorCreatingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fika Client Version:.
        /// </summary>
        internal static string FikaClientStatusTitle {
            get {
                return ResourceManager.GetString("FikaClientStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fika Server Version:.
        /// </summary>
        internal static string FikaServerStatusTitle {
            get {
                return ResourceManager.GetString("FikaServerStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Profile Loaded.
        /// </summary>
        internal static string NoActiveProfileLoaded {
            get {
                return ResourceManager.GetString("NoActiveProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profile Found.
        /// </summary>
        internal static string NoProfileFound {
            get {
                return ResourceManager.GetString("NoProfileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profile has been found. Would you like to you create one with your current game data?.
        /// </summary>
        internal static string NoProfileFoundCreateQ {
            get {
                return ResourceManager.GetString("NoProfileFoundCreateQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile {0} is corrupted or missing and will not be loaded..
        /// </summary>
        internal static string ProfileCorruptedMsg {
            get {
                return ResourceManager.GetString("ProfileCorruptedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} Corrupted or Missing....
        /// </summary>
        internal static string ProfileCorruptedProgressMsg {
            get {
                return ResourceManager.GetString("ProfileCorruptedProgressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Corrupted or Missing.
        /// </summary>
        internal static string ProfileCorruptedTitle {
            get {
                return ResourceManager.GetString("ProfileCorruptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} Created!.
        /// </summary>
        internal static string ProfileCreated {
            get {
                return ResourceManager.GetString("ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile {0} Successfully Loaded!.
        /// </summary>
        internal static string ProfileLoaded {
            get {
                return ResourceManager.GetString("ProfileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPT install was not found in the current folder. Ikaprofile must be installed in the SPT directory. The application will now terminate..
        /// </summary>
        internal static string SPTNotFound {
            get {
                return ResourceManager.GetString("SPTNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkov executable was not found in the current folder. Ikaprofile must be installed in the SPT directory. The application will now terminate..
        /// </summary>
        internal static string TarkovNotFound {
            get {
                return ResourceManager.GetString("TarkovNotFound", resourceCulture);
            }
        }
    }
}
